# Artificial Neural Network

### Importing the libraries

In [21]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [22]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [23]:
dataset = pd.read_excel('/content/Folds5x2_pp.xlsx')

print(dataset.head())

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90


In [24]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [25]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)



## Part 2 - Building the ANN

### Initializing the ANN

In [27]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [30]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [31]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size=32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6198
Epoch 2/100
240/240 [==============================] - 0s 987us/step - loss: 26.7548
Epoch 3/100
240/240 [==============================] - 0s 999us/step - loss: 26.9230
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6193
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 27.2693
Epoch 6/100
240/240 [==============================] - 0s 988us/step - loss: 26.7829
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6102
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 26.9595
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 26.5296
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6223
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2476
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 26.

### Predicting the results of the Test set

In [36]:
y_pred = ann.predict(X_test)

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[431.   431.23]
 [461.98 460.01]
 [465.45 461.14]
 ...
 [472.72 473.26]
 [439.49 438.  ]
 [458.72 463.28]]


In [39]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_pred))

24.64055885301504


# Let's try other models

## linear regression

In [40]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)


print(mean_squared_error(y_test, y_pred))



19.733699303497648
